% Auto-generated by cameraCalibrator app on 07-Apr-2023
%-------------------------------------------------------


% Define images to process
imageFileNames = {'/home/gopisainath/EECE5554/LAB5/pics/WhatsApp Image 2023-04-07 at 14.24.12.jpeg',...
    '/home/gopisainath/EECE5554/LAB5/pics/WhatsApp Image 2023-04-07 at 14.24.13 (1).jpeg',...
    '/home/gopisainath/EECE5554/LAB5/pics/WhatsApp Image 2023-04-07 at 14.24.13 (2).jpeg',...
    '/home/gopisainath/EECE5554/LAB5/pics/WhatsApp Image 2023-04-07 at 14.24.13 (3).jpeg',...
    '/home/gopisainath/EECE5554/LAB5/pics/WhatsApp Image 2023-04-07 at 14.24.13 (4).jpeg',...
    '/home/gopisainath/EECE5554/LAB5/pics/WhatsApp Image 2023-04-07 at 14.24.13 (5).jpeg',...
    '/home/gopisainath/EECE5554/LAB5/pics/WhatsApp Image 2023-04-07 at 14.24.13 (6).jpeg',...
    '/home/gopisainath/EECE5554/LAB5/pics/WhatsApp Image 2023-04-07 at 14.24.13 (7).jpeg',...
    '/home/gopisainath/EECE5554/LAB5/pics/WhatsApp Image 2023-04-07 at 14.24.13.jpeg',...
    '/home/gopisainath/EECE5554/LAB5/pics/WhatsApp Image 2023-04-07 at 14.24.14.jpeg',...
    };
% Detect calibration pattern in images
detector = vision.calibration.monocular.CheckerboardDetector();
[imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates for the planar pattern keypoints
squareSize = 25;  % in units of 'millimeters'
worldPoints = generateWorldPoints(detector, 'SquareSize', squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
